
services:
  backend:
    build: 
      context: ./backend
    container_name: toolkitz-backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PORT=3000

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=YOUR_LAPTOP_IP/api # -> change YOUR_LAPTOP_API to 192.168.xxxxx
    container_name: toolkitz-frontend
    ports:
      - "80:80" # Akses web via http://localhost
    restart: unless-stopped
    depends_on:
      - backend
